### ISSUE TITLE
カウンター来店予約

### ISSUE THREAD

**Issue by seiyakidokoro** [seiyakidokoro/dev#7]
# TODO
- [ ] ここにTODO
# View
## index
- [ ] 
  - [ ] 
## index-smp
- [ ] 
## confirm
- [ ] 
## confirm-smp
- [ ] 
## complete
- [ ] 
## complete_smp
- [ ] 
## javascript
- [ ] 
#  Mailer
- [ ] user
  - [ ] 
- [ ] admin
  - [ ] 
# Controller
- [ ] index
- [ ] edit
- [ ] confirm
- [ ] complete
    - [ ] member_idの保存 
# Model
- [ ] 
# Setting
- [ ] Settings.reform_info_mail.user.subject
- [ ] Settings.reform_info_mail.company.subject
    - [ ] .gsub(':name')の確認
- [ ] Settings.reform_info_mail.admin.subject
